# data Structures in python

# LISTS

In [11]:
#list---> a collection of numerics or strings or lists itself(H2)
# a list is always given by []

In [21]:
x=[1,2,3,"Python"]

In [23]:
x[2]="Nitish"
x

[1, 2, 'Nitish', 'Python']

In [26]:
#indexing in python
print x[0]
print x[-1]# prints the last element

1
Python


In [27]:
x[0:3]

[1, 2, 3]

In [29]:
#x[4]="R" will also give error. 
#use append functio to add elements to a list, not like this

In [15]:
x.append(["R"])

<function sort>

In [17]:
#a list can have lists within ie nested lists
#example
x.append(["Data","Science",4,5,6])

In [18]:
print x

[1, 2, 3, 'Python', 'R', ['R'], ['Data', 'Science', 4, 5, 6]]


In [34]:
#Task 1--> get me "Science out of x above using indexing in python"

In [19]:
#insert elements at a particular position
x.insert(0,'A')
x

['A', 1, 2, 3, 'Python', 'R', ['R'], ['Data', 'Science', 4, 5, 6]]

# Dictionaries in Python

In [24]:
y={"emp#1":"Raj",
  "emp#2":"Vijay",
  "emp#3":"Ramesh",
  "emp#4":"XY"}
print(y)

{'emp#4': 'XY', 'emp#2': 'Vijay', 'emp#3': 'Ramesh', 'emp#1': 'Raj'}


In [42]:
#When you create the dictionary, python doesn't care about in what
# order you wrote the elements and it won't remember the order after
# the object is created. You cannot expect it(regular dictionary) to 
#print in the same order. 

In [26]:
#Python dictionary is an unordered ( cannot be accessed by indexes) collection of items
#dictionaries are always given by {} and have key:value pair
y={"emp#1":"Raj",
  "emp#2":"Vijay",
  "emp#3":"Ramesh"}
my_dict = {'name': 'John', 1: [2, 4, 3]}

In [29]:
y.keys()

['emp#2', 'emp#3', 'emp#1']

In [47]:
print y.keys()
print y.values()

['emp#2', 'emp#3', 'emp#1']
['Vijay', 'Ramesh', 'Raj']


In [48]:
print y['emp#1'] # values can be accessed by their keys

Raj


In [49]:
#update a value by using its key
y['emp#2']="Suresh"

In [50]:
print y

{'emp#2': 'Suresh', 'emp#3': 'Ramesh', 'emp#1': 'Raj'}


In [51]:
#to delete items
del y['emp#3']

In [52]:
print y

{'emp#2': 'Suresh', 'emp#1': 'Raj'}


In [53]:
y.clear();     # remove all entries in dict , leaves an empty dictionary

In [54]:
del y        # delete entire dictionary

In [55]:
dict = {'Name': 'Zara', 'Age': 7, 'Name': 'Manni'} #duplicate keys

In [56]:
dict['Name']#the last value wins

'Manni'

In [30]:
y={"k1":"v1","k2":{1:[1,2,3]}}

In [37]:
y["k2"][1][0]="A"
print(y)

{'k2': {1: ['A', 2, 3]}, 'k1': 'v1'}


In [38]:
dict = {['Name']: 'Zara', 'Age': 7} #Keys must be immutable.--which means they cannot
#be chnaged once assigned 
#Which means you can use strings, numbers 
#or tuples as dictionary keys but something like ['key'] is not allowed
#We can use arbitrary types as values in a dictionary, 
#but there is a restriction for the keys. 
#Only immutable data types can be used as keys, 
#i.e. no lists or dictionaries can be used as keys

TypeError: unhashable type: 'list'

In [58]:
#It's kinda like having all your CDs neatly alphabetised on shelves, rather than stacked randomly
#out of their cases on top of your speakers. Dictionaries know where it's at, I'm telling you.
#But there's a price to pay for dictionaries' ability to keep it together. Remember
#when I said that the dictionary calculates a hash based on the item's content? Well,
#what happens if that content changes? For immutable objects that's not a problem - 
#their content can't change - but mutable objects, by definition, 
#can change their contents, and when they do, their hash (if they even have one)
#will change too. Which is cool, obviously, not everyone wants to be put in a box, I get that,
#but if the hash has changed, there's no way for the dictionary to work out where it put the thing.

In [59]:
# add item in a dictonary
print dict
dict['address'] = 'Downtown'  

{'Age': 7, 'Name': 'Manni'}


In [60]:
print dict

{'Age': 7, 'Name': 'Manni', 'address': 'Downtown'}


In [62]:
#Iterating Through a Dictionary
for i in dict:
    print(dict[i])
    
#or
for val in dict.values():
    print val

7
Manni
Downtown
7
Manni
Downtown


In [64]:
for i in dict:
    print i
    
#or
for val in dict.keys():
    print val

Age
Name
address
Age
Name
address


In [68]:
print(sorted(y))#Return a new sorted list of keys in the dictionary.

['emp#1', 'emp#2', 'emp#3', 'emp#4']


In [ ]:
#DIFFERENCE BETWEEN LISTS AND DICTIONARIES
#Lists are ordered sets of objects, whereas dictionaries are unordered sets
#items in dictionaries are accessed via keys and not via their position

In [69]:
#Tuple as keys are okay, as you can see in the following example
dic = { (1,2,3):"abc", 3.1415:"abcd"}
print dic
print dic[(1,2,3)]

{3.1415: 'abcd', (1, 2, 3): 'abc'}
abc


In [15]:
#convert dictionary to a list
print dic.items()#gives a list with first element as one 
#key,value pair, and so on..
print dic.keys()
print dic.values()

[(3.1415, 'abcd'), ((1, 2, 3), 'abc')]
[3.1415, (1, 2, 3)]
['abcd', 'abc']


In [70]:
#convert list to a dictionary
list1=[1,2,3]
list2=["A","B","C"] #if the 2 lists were of unequal size, 
#the extra item will be ignored
dic1=zip(list1,list2) #then use the dict function
print dic1

[(1, 'A'), (2, 'B'), (3, 'C')]


In [73]:
dic2=dict(dic1)
print dic2

{1: 'A', 2: 'B', 3: 'C'}


In [ ]:
d1={'key1':40,
   'key2':50}

d2={'key1':555}
d1+d2 #this gives an error,dictionaries cannot be 
#added or substracted or multiplied

# TUPLES

In [ ]:
#A tuple is a sequence of immutable Python objects. Tuples are sequences,
#just like lists. The differences between tuples and lists are, the tuples
#cannot be changed unlike lists and tuples use parentheses, whereas lists use square brackets.

In [14]:
type(x)

tuple

In [13]:
x=(1,2,3)

In [15]:
x[0]

1

In [16]:
x[0]=4 #this will give an error 
#tuples are immutable.i.e once assigned a value it cant be changed

TypeError: 'tuple' object does not support item assignment

In [90]:
tup1 = ('physics', 'chemistry', 1997, 2000)

In [17]:
tup1 = (50)
print (type(tup1)) #will give int
#so To write a tuple containing a single value you 
#have to include a comma, even though there is only one value
tup1 = (50,)
print (type(tup1))

<type 'int'>
<type 'tuple'>


In [94]:
#If you have data that doesn't change, implementing it as tuple will 
#guarantee that it remains write-protected.

# Set

In [ ]:
#A Set is an unordered collection data type that is iterable, immutable,
#and has no duplicate elements. Python’s set class represents the mathematical
#notion of a set. The major advantage of using a set, as opposed to a list,
#is that it has a highly optimized method for checking whether a 
#specific element is contained in the set.

In [41]:
x={1,2,3}
print x
x={1,1,1,2,3,4,5,6,7,4,3,2}
print x

set([1, 2, 3])
set([1, 2, 3, 4, 5, 6, 7])


In [42]:
my_set = {1.0, "Hello", (1, 2, 3),(1.0,2.0)}
print my_set

set([(1.0, 2.0), 1.0, 'Hello', (1, 2, 3)])


In [43]:
my_set = set([1,2,3,2])# we can make set from a list
print(my_set)

set([1, 2, 3])


In [44]:
#add element
my_set.add(22)
print(my_set)

set([1, 2, 3, 22])


In [45]:
my_set.update([12,13,14])
print(my_set)

set([1, 2, 3, 12, 13, 14, 22])


In [102]:
my_set[0] #set does not support indexing, so error

In [103]:
my_set.discard(22)# discard an element
print(my_set)

set([1, 2, 3, 12, 13, 14])


In [104]:
my_set.remove(12)# remove an element
print(my_set)

set([1, 2, 3, 13, 14])


In [107]:
my_set.discard(222)# discard an element not present in my_set
print(my_set)

set([1, 3, 13, 14])


In [48]:
x={1,2,3,(2,3,4)}
print(x)

set([1, (2, 3, 4), 3, 2])


In [ ]:
my_set.remove(222) #remove an element not present in my_set gives error

# LOOPS IN PYTHON

In [50]:
x=[1,2,3]
#for loop in python
for i in x:
    print i

1
2
3


In [109]:
#while loop in python
i=5
while i<10:
    print i#inside first loop
    if(i<8):
        print i#inside second loop
    i=i+1

5
5
6
6
7
7
8
9


In [110]:
#if elif else
if i<4:
    print "i is less than 4"
elif i>4:
    print "i is more than 4"
else:
    print "i is equal to 4"

i is more than 4


In [53]:
range(1,30,5)

[1, 6, 11, 16, 21, 26]

In [111]:
# Prints out the numbers 0,1,2,3,4
for x in range(5):
    print(x)

0
1
2
3
4


In [112]:
# Prints out 3,5,7
for x in range(3, 8, 2):
    print(x)

3
5
7


In [21]:
#"break" and "continue" statements
# Prints out 0,1,2,3,4
#break will come out of all loops
count = 0
while True:
    print(count)
    count += 1
    if count >= 5:
        break       
print "******"
# Prints out only odd numbers - 1,3,5,7,9
# continue comes out of the current loop
for x in range(10):
    # Check if x is even
    if x % 2 == 0:
        continue
    print(x)

0
1
2
3
4
******
1
3
5
7
9


# comprehension in python

In [117]:
alist=[1,2,3,4]
#multiply each element by 2
for i in alist:
    print i*2

2
4
6
8


In [118]:
[i*2 for i in alist]

[2, 4, 6, 8]

In [119]:
words = 'The quick brown fox jumps over the lazy dog'.split()
print words

['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']


In [120]:
stuff = [[w.upper(), w.lower(), len(w)] for w in words]

In [122]:
for i in stuff:
    print i

['THE', 'the', 3]
['QUICK', 'quick', 5]
['BROWN', 'brown', 5]
['FOX', 'fox', 3]
['JUMPS', 'jumps', 5]
['OVER', 'over', 4]
['THE', 'the', 3]
['LAZY', 'lazy', 4]
['DOG', 'dog', 3]


In [131]:
#print even numbers between 1 to 20
[i for i in range(1,20) if i%2==0]

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [134]:
#list comprehension creates the Pythagorean triples: 
[(x,y,z) for x in range(1,30) for y in range(x,30) for z in range(y,30) if x**2 + y**2 == z**2]

[(3, 4, 5),
 (5, 12, 13),
 (6, 8, 10),
 (7, 24, 25),
 (8, 15, 17),
 (9, 12, 15),
 (10, 24, 26),
 (12, 16, 20),
 (15, 20, 25),
 (20, 21, 29)]

In [137]:
#find intersection of 2 lists
x=[1,2,3]
y=[2,3,4,5]
[i for i in x if i in y]

[2, 3]

In [138]:
#elements in first but not in second
[val for val in x if val not in y]

[1]

In [139]:
#elements in first but not in second
[val for val in y if val not in x]

[4, 5]

# array

In [1]:
#NumPy array, formally called ndarray 
#elements are of the same type. if different it converts to the most complex type
import numpy as np

In [2]:
x=[1,2,3]
xx=np.array(x)
type(xx)

numpy.ndarray

In [3]:
xx

array([1, 2, 3])

In [25]:
x=['A',1,2,3]
xx=np.array(x)
print xx

['A' '1' '2' '3']


In [4]:
x=np.array(range(20))

In [5]:
print x

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [8]:
y=x.reshape(2,10)
#y1=x.reshape(5,7) gives an error--total size of new array must be unchanged

In [13]:
print y
print("\n")
print y>5

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


[[False False False False False False  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [9]:
print y[0,[1,3]]
#accessing individual elements of an array
#syntax is --->  name_of_array[ row#, column#]
print y[0,0]
print y[0,1]
print y[1,4]
#print y[2,1] #this gives an error
print y[1,3:]

print [y[0,i] for i in [0,3,4,5,7]]# to print randomly

[1 3]
0
1
14
[13 14 15 16 17 18 19]
[0, 3, 4, 5, 7]


In [172]:
y.max()

19

In [30]:
print y[y>5] #gives all elements which satisfy the condition
print y[y>5].shape # its shape is made 1D & output is a array
print "*****"
print type(y[y>5])
print "*----*"
print (y>5)
print type(y>5)
print "*//////*"
print ([y>5])
print type([y>5])

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(14L,)
*****
<type 'numpy.ndarray'>
*----*
[[False False False False False False  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]
<type 'numpy.ndarray'>
*//////*
[array([[False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)]
<type 'list'>


In [166]:
y.shape # gives the number of rows and columns

(2L, 10L)

In [168]:
np.random.rand(10) #gives 10 random numbers between 0 & 1 from a uniform dist

array([ 0.93826524,  0.69678702,  0.48642552,  0.48998651,  0.05299345,
        0.83198769,  0.62092411,  0.21471579,  0.8986779 ,  0.87697409])

In [31]:
#gives 10 numbers from a normal dist wth mean 0 and sd=1
np.random.randn(10) 

array([ 0.76992303, -1.39438325,  0.47769164,  0.92346502,  0.1694653 ,
        1.22525576,  1.55016235,  2.85516446, -0.14443723,  0.15017518])

In [32]:
#linspace(start, stop, N)# N evenly spaced points between start & Stop
x=np.linspace(1,20,6)
print x

[  1.    4.8   8.6  12.4  16.2  20. ]


In [33]:
x=([1,2,3])# if its a list, it repeats 2 times
print type(x)
print x*2
#if its an array it mutiplies
x=np.array([1,2,3])
print x*2

<type 'list'>
[1, 2, 3, 1, 2, 3]
[2 4 6]


In [218]:
a=[1,2,3]
b=[3,4,5]
print a+b #if a and b are lists
print np.array(a)+np.array(b)#if a and b are arrays [They must be of same length]

[1, 2, 3, 3, 4, 5]
[4 6 8]


In [225]:
x=np.array(a)
y=np.array(b)
x[1:]-y[:-1] #break it into individual pieces to understand

array([-1, -1])

In [228]:
#forming a 2D array
x=np.array([[1,2,3],[5,6,7]])
print x
print x.shape

[[1 2 3]
 [5 6 7]]
(2L, 3L)


In [231]:
#difference between numpy arrays and lists
#1) same datatype vs multiple datatypes
#2) numpy arrays support vectorised operations. eg, multiple each element by a
# constant etc. lists cannnot do that
#3) easy to add elements to lists(append function) but n0t to arrays

# Series

In [37]:
import pandas as pd

In [191]:
#series
#One-dimensional array with axis labels
label=["A","B","C"]
data=[10,20,30]

In [193]:
arr=np.array(data)
type(label),type(data),type(arr)

(list, list, numpy.ndarray)

In [235]:
aseries=pd.Series(data=data,index=label)

In [236]:
print aseries

A    10
B    20
C    30
dtype: int64


# DataFrame

In [196]:
df=pd.DataFrame(data=arr,index=label,columns=['column_one'])

In [197]:
df

column_one
A          10
B          20
C          30

In [201]:
#to access columns in a dataframe--> dataframe_name['columnName']
df['column_one'] #output is of type series
#OR
df.column_one

A    10
B    20
C    30
Name: column_one, dtype: int32

In [42]:
#np.array([1,2,3,4]).reshape(2,2)
pd.DataFrame(data=np.array([1,2,3,4]).reshape(2,2),columns=[['A','B']])

A  B
0  1  2
1  3  4

In [ ]:
#Features of DataFrame
#each column is an array
#columns can be of different data type
#dataframes are like excel spreadsheet or SQL tables

In [44]:
#if no row index or column name is given, it takes 0,1,2,3,.. by default

In [46]:
df = pd.DataFrame() #empty dataframe
print df

Empty DataFrame
Columns: []
Index: []


In [50]:
#creating dataframe from LISTS
import pandas as pd
data = [['Alex',10],[3,12],['Clarke',13]]
print data
df = pd.DataFrame(data,columns=['Name','Age'])
print df
#***************
#ideally dataframes shud be created from multiple arrays
#(since they have same data type)
#else we may get different data type in the same column
#which though allwed but is wrong
#***************

[['Alex', 10], [3, 12], ['Clarke', 13]]
     Name  Age
0    Alex   10
1       3   12
2  Clarke   13


In [55]:
import pandas as pd
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print df
#dtype parameter changes Age to float

     Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0


In [57]:
##creating dataframe from LISTS
import pandas as pd
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data,dtype=float)
print df

    Age   Name
0  28.0    Tom
1  34.0   Jack
2  29.0  Steve
3  42.0  Ricky


In [58]:
import pandas as pd
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])#to give our 
#own index to the rows
print df

       Age   Name
rank1   28    Tom
rank2   34   Jack
rank3   29  Steve
rank4   42  Ricky


In [59]:
#del a column
#del df['columnName']
#or
#df.drop(['columnName'],axis=1,inplace=True)
#inplace=True is used to overwrite

In [60]:
df.drop(['Age'],axis=1)#without inplace=True it just prints the result

Name
rank1    Tom
rank2   Jack
rank3  Steve
rank4  Ricky

In [3]:
from numpy.random import randn
df = pd.DataFrame(np.random.rand(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
print df

          W         X         Y         Z
A  0.534119 -1.221335  0.701937  0.322365
B -0.549228 -1.009990  0.409683 -0.940183
C -1.317233  0.956588 -0.583541  1.571661
D -0.827233  1.268702 -0.889876 -1.103983
E  1.188144 -1.210317  0.090285 -1.821395


# Selection and Indexing

In [4]:
#to access multiple columns
# Pass a list of column names
df[['W','Z']]

W         Z
A  0.534119  0.322365
B -0.549228 -0.940183
C -1.317233  1.571661
D -0.827233 -1.103983
E  1.188144 -1.821395

In [5]:
type(df['W'])#DataFrame Columns are just Series

pandas.core.series.Series

In [6]:
df['new'] = df['W'] + df['Y'] #creating a new columns
print df

In [7]:
df.drop('new',axis=1,inplace=True)
print df

In [9]:
#selecting rows
print df.loc['A']  #use loc if yu want to access by row label
print df.iloc[2]   #use iloc if yu want to access by row index

W    0.534119
X   -1.221335
Y    0.701937
Z    0.322365
Name: A, dtype: float64
W   -1.317233
X    0.956588
Y   -0.583541
Z    1.571661
Name: C, dtype: float64


In [11]:
df[df>0]

W         X         Y         Z
A  0.534119       NaN  0.701937  0.322365
B       NaN       NaN  0.409683       NaN
C       NaN  0.956588       NaN  1.571661
D       NaN  1.268702       NaN       NaN
E  1.188144       NaN  0.090285       NaN

In [12]:
df[df['W']>0]

W         X         Y         Z
A  0.534119 -1.221335  0.701937  0.322365
E  1.188144 -1.210317  0.090285 -1.821395

In [13]:
df[df['W']>0]["W"]

A    0.534119
E    1.188144
Name: W, dtype: float64

In [16]:
#For two conditions you can use | and & with parenthesis
df[(df['W']>0) & (df['Y'] > 0.2)]

W         X         Y         Z
A  0.534119 -1.221335  0.701937  0.322365

In [1]:
import pandas as pd

In [ ]:
pd.DataFrame()